name: math_wizard_mk2
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.16.0
  provider: ^4.0.5
  rflutter_alert: ^1.0.3
  google_sign_in: ^4.4.1
  image_picker: ^0.6.5
  firebase_storage: ^3.1.5
  cloud_firestore: ^0.13.5
  custom_switch: ^0.0.1
  modal_progress_hud: ^0.1.3
  firebase_database: ^3.1.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_screenutil: ^0.4.2
  percent_indicator: "^2.1.1"
  font_awesome_flutter: ^8.4.0
  auto_size_text: ^2.0.0+2
  material_design_icons_flutter: 4.0.5045
  flutter_custom_clippers: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
   - assets/image_01.png
   - assets/image_02.png
   - assets/logo.png
   - assets/bg.png
   - assets/bg1.png
   - assets/avatar1.png
   - assets/materi_book.png
   - assets/trophy.png
   - assets/trophy-gold.png
   - assets/trophy-silver.png
   - assets/trophy-bronze.png
   - assets/coin.png
   - assets/pattern.png
   - assets/pattern.jpg
   - assets/bg2.png
   - assets/bg3.png
   - assets/Final Icons/CatIcon1.png
   - assets/Final Icons/CatIcon2.png
   - assets/Final Icons/CatIcon3.png
   - assets/Final Icons/CatIcon4.png
   - assets/Final Icons/DogIcon1.png
   - assets/Final Icons/DogIcon3.png
   - assets/Final Icons/RacoonIcon1.png
   - assets/img/body.png
   - assets/img/angle.png
   - assets/img/axis.png
   - assets/img/brackets.png
   - assets/img/brackets-1.png
   - assets/img/calculator-1.png
   - assets/img/compass.png
   - assets/img/cone.png
   - assets/img/cube.png
   - assets/img/cylinder.png
   - assets/img/division.png
   - assets/img/empty-set.png
   - assets/img/equal.png
   - assets/img/equation.png
   - assets/img/function.png
   - assets/img/gravity.png
   - assets/img/maths.png
   - assets/img/minus.png
   - assets/img/plus.png
   - assets/img/percentage.png
   - assets/img/pi.png
   - assets/img/pie-chart.png
   - assets/img/protractor.png
   - assets/img/pyramid.png
   - assets/img/set-square.png
   - assets/img/square-root.png
   - assets/img/sphere.png
   - assets/img/triangle.png
   - assets/img/failed.png
   - assets/img/success.png
   - assets/img/infinity.png
   - assets/img/body.png
   - assets/img/abacus.png
   - assets/img/pencil.png
   - assets/img/multiply.png
   - assets/img/planet.jpg
   - assets/img/calculator.png
   - assets/img/panel.png
   - assets/img/notebook.png
   - assets/google-logo.png
   - assets/facebook-logo.png
   - assets/gold-medal.png
   - assets/silver-medal.png
   - assets/bronze-medal.png
   - assets/medal.png
   - assets/four.png
   - assets/five.png
   - assets/six.png
   - assets/seven.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: assets/Poppins-Medium.ttf   

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
